kind: ResourceQuota
apiVersion: v1
metadata:
  name: compute-long-running-quota
  namespace: devops-xray
spec:
  hard:
    limits.cpu: '20'
    limits.memory: 32Gi
    pods: '100'
    requests.cpu: '4'
    requests.memory: 16Gi
  scopes:
    - NotTerminating
    - NotBestEffort
