kind: ResourceQuota
apiVersion: v1
metadata:
  name: compute-long-running-quota
  namespace: devops-xray
spec:
  hard:
    limits.cpu: '32'
    limits.memory: 64Gi
    pods: '100'
    requests.cpu: '16'
    requests.memory: 32Gi
  scopes:
    - NotTerminating
    - NotBestEffort
